import { DarkTheme, DefaultTheme, type Theme } from "@react-navigation/native";

export const THEME = {
  light: {
    background: "hsl(37 87% 97%)",
    foreground: "hsl(28 16% 21%)",
    card: "hsl(0 0% 100%)",
    cardForeground: "hsl(28 16% 21%)",
    popover: "hsl(36 83% 98%)",
    popoverForeground: "hsl(28 16% 21%)",
    primary: "hsl(17 54% 54%)",
    primaryForeground: "hsl(37 87% 97%)",
    secondary: "hsl(37 71% 64%)",
    secondaryForeground: "hsl(28 16% 21%)",
    muted: "hsl(35 42% 91%)",
    mutedForeground: "hsl(30 10% 44%)",
    accent: "hsl(37 32% 87%)",
    accentForeground: "hsl(28 16% 21%)",
    destructive: "hsl(6 41% 51%)",
    destructiveForeground: "hsl(0 0% 100%)",
    border: "hsl(34 30% 86%)",
    input: "hsl(35 42% 91%)",
    ring: "hsl(17 54% 54%)",
    radius: "1rem",
  },
  dark: {
    background: "hsl(30 9% 9%)",
    foreground: "hsl(39 33% 90%)",
    card: "hsl(30 10% 12%)",
    cardForeground: "hsl(39 33% 90%)",
    popover: "hsl(30 9% 9%)",
    popoverForeground: "hsl(39 33% 90%)",
    primary: "hsl(17 65% 65%)",
    primaryForeground: "hsl(30 9% 9%)",
    secondary: "hsl(36 59% 59%)",
    secondaryForeground: "hsl(30 9% 9%)",
    muted: "hsl(34 9% 15%)",
    mutedForeground: "hsl(33 9% 57%)",
    accent: "hsl(33 9% 19%)",
    accentForeground: "hsl(39 33% 90%)",
    destructive: "hsl(5 39% 45%)",
    destructiveForeground: "hsl(0 0% 100%)",
    border: "hsl(33 9% 19%)",
    input: "hsl(30 10% 12%)",
    ring: "hsl(17 65% 65%)",
    radius: "1rem",
  },
} as const;

export const NAV_THEME: Record<"light" | "dark", Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};